package logic

import (
	"encoding/json"
	"fmt"
	"github.com/compose-spec/compose-go/v2/cli"
	"github.com/donknap/dpanel/common/accessor"
	"github.com/donknap/dpanel/common/dao"
	"github.com/donknap/dpanel/common/entity"
	"github.com/donknap/dpanel/common/function"
	"github.com/donknap/dpanel/common/migrate"
	"github.com/donknap/dpanel/common/service/compose"
	"github.com/donknap/dpanel/common/service/docker"
	"github.com/donknap/dpanel/common/service/exec"
	"github.com/donknap/dpanel/common/service/storage"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

const (
	ComposeTypeText        = "text"
	ComposeTypeRemoteUrl   = "remoteUrl"
	ComposeTypeServerPath  = "serverPath"
	ComposeTypeStoragePath = "storagePath"
)

// docker compose 任务执行，包含 部署，销毁，控制
type task struct {
	entity *entity.Compose
}

func (self task) composer() (*compose.Wrapper, error) {
	options := make([]cli.ProjectOptionsFn, 0)

	options = append(options, cli.WithName(self.entity.Name))

	if !function.IsEmptyArray(self.entity.Setting.Environment) {
		envList := make([]string, 0)
		for _, item := range self.entity.Setting.Environment {
			envList = append(envList, fmt.Sprintf("%s=%s", item.Name, item.Value))
		}
		options = append(options, cli.WithEnv(envList))
	}

	yamlFilePath := ""
	if self.entity.Setting.Type == ComposeTypeServerPath {
		yamlFilePath = self.entity.Setting.Uri
	} else if self.entity.Setting.Type == ComposeTypeStoragePath {
		yamlFilePath = filepath.Join(storage.Local{}.GetComposePath(), self.entity.Setting.Uri)
	} else {
		yamlFilePath = filepath.Join(storage.Local{}.GetComposePath(), self.entity.Name, "compose.yaml")
		err := os.MkdirAll(filepath.Dir(yamlFilePath), os.ModePerm)
		if err != nil {
			return nil, err
		}
		if self.entity.Setting.Type == ComposeTypeRemoteUrl {
			response, err := http.Get(self.entity.Yaml)
			if err != nil {
				return nil, err
			}
			defer func() {
				_ = response.Body.Close()
			}()
			content, err := io.ReadAll(response.Body)
			if err != nil {
				return nil, err
			}
			self.entity.Yaml = string(content)
		}
		err = os.WriteFile(yamlFilePath, []byte("# 此文件由 dpanel 面板生成，请勿修改！ \n# Generated by dpanel, do not modify!\n"+self.entity.Yaml), 0666)
		if err != nil {
			return nil, err
		}
	}
	options = append(options, compose.WithYamlPath(yamlFilePath))
	// 生成覆盖Yaml
	if !function.IsEmptyArray(self.entity.Setting.Override) {
		yamlOverrideFilePath := filepath.Join(storage.Local{}.GetComposePath(), self.entity.Name, "compose-override.yaml")
		err := os.MkdirAll(filepath.Dir(yamlOverrideFilePath), os.ModePerm)
		if err != nil {
			return nil, err
		}
		overrideProject := migrate.Upgrade20241014{}.Covert(self.entity.Setting.Override)
		overrideYaml, _ := overrideProject.MarshalYAML()
		err = os.WriteFile(
			yamlOverrideFilePath,
			append(
				[]byte("# 此文件由 dpanel 面板生成，请勿修改！ \n# Generated by dpanel, do not modify!\n"),
				overrideYaml...,
			), 0666)
		if err != nil {
			return nil, err
		}
		options = append(options, compose.WithYamlPath(yamlOverrideFilePath))
	}
	composer, err := compose.NewCompose(options...)

	if err != nil {
		return nil, err
	}
	return composer, nil
}

func (self task) Deploy() error {
	composer, err := self.composer()
	if err != nil {
		return err
	}
	cmd := composer.GetBaseCommand()
	Compose{}.runCommand(append(cmd, "--progress", "tty", "up", "-d"))

	// todo 部署完成后还需要把外部容器加入到对应的网络中
	// 如果 compose 中未指定网络，则默认的名称为 项目名_default

	return nil
}

func (self task) Destroy(deleteImage bool) error {
	composer, err := self.composer()
	if err != nil {
		return err
	}
	cmd := composer.GetBaseCommand()
	// todo 删除compose 前需要先把关联的已有容器网络退出

	cmd = append(cmd, "--progress", "tty", "down")
	if deleteImage {
		cmd = append(cmd, "--rmi", "all")
	}
	Compose{}.runCommand(cmd)
	return nil
}

func (self task) Ctrl(op string) error {
	composer, err := self.composer()
	if err != nil {
		return err
	}
	cmd := composer.GetBaseCommand()
	Compose{}.runCommand(append(cmd, "--progress", "tty", op))
	return nil
}

func (self task) Yaml() ([]byte, error) {
	composer, err := self.composer()
	if err != nil {
		return nil, err
	}
	return composer.Project.MarshalYAML()
}

type composeContainerResult struct {
	Name string `json:"name"`
}

func (self task) Ps() []*composeContainerResult {
	result := make([]*composeContainerResult, 0)
	if self.entity.Name == "" {
		return result
	}
	composer, err := self.composer()
	if err != nil {
		return result
	}
	cmd := composer.GetBaseCommand()
	cmd = append(cmd, "ps", "--format", "json", "--all")
	out := exec.Command{}.RunWithOut(&exec.RunCommandOption{
		CmdName: "docker",
		CmdArgs: append(append(docker.Sdk.ExtraParams, "compose"), cmd...),
	})
	if out == "" {
		return result
	}
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(line, "{") {
			temp := composeContainerResult{}
			err = json.Unmarshal([]byte(line), &temp)
			if err == nil {
				result = append(result, &temp)
			}
		}
	}
	return result
}

type Compose struct {
}

type composeItem struct {
	Name        string `json:"name"`
	Status      string `json:"status"`
	ConfigFiles string `json:"configFiles"`
}

func (self Compose) GetTasker(entity *entity.Compose) *task {
	tasker := &task{
		entity: entity,
	}
	return tasker
}

func (self Compose) Ls(projectName string) []*composeItem {
	command := []string{
		"ls",
		"--format", "json",
		"--all",
	}
	if projectName != "" {
		command = append(command, "--filter", "name="+projectName)
	}
	out := exec.Command{}.RunWithOut(&exec.RunCommandOption{
		CmdName: "docker",
		CmdArgs: append(append(docker.Sdk.ExtraParams, "compose"), command...),
	})
	result := make([]*composeItem, 0)
	err := json.Unmarshal([]byte(out), &result)
	if err != nil {
		return result
	}
	return result
}

func (self Compose) Kill() error {
	return exec.Command{}.Kill()
}

func (self Compose) runCommand(command []string) {
	exec.Command{}.RunInTerminal(&exec.RunCommandOption{
		CmdName: "docker",
		CmdArgs: append(
			append(docker.Sdk.ExtraParams, "compose"),
			command...,
		),
	})
}

func (self Compose) Sync() error {
	composeList, _ := dao.Compose.Find()

	composeFileName := []string{
		"docker-compose.yml", "docker-compose.yaml",
		"compose.yml", "compose.yaml",
	}
	rootDir := storage.Local{}.GetComposePath()
	err := filepath.Walk(rootDir, func(path string, info fs.FileInfo, err error) error {
		for _, suffix := range composeFileName {
			if strings.HasSuffix(path, suffix) {
				rel, _ := filepath.Rel(rootDir, path)
				// 只同步二级目录下的 yaml
				if segments := strings.Split(filepath.Clean(rel), string(filepath.Separator)); len(segments) == 2 {
					name := filepath.Dir(rel)

					has := false
					for _, item := range composeList {
						if item.Name == name {
							has = true
							break
						}
					}

					if !has {
						dao.Compose.Create(&entity.Compose{
							Title: "",
							Name:  name,
							Yaml:  rel,
							Setting: &accessor.ComposeSettingOption{
								Type:   ComposeTypeStoragePath,
								Status: "waiting",
								Uri:    rel,
							},
						})
					}
				}
				break
			}
		}
		return nil
	})
	if err != nil {
		return err
	}
	return nil
}
