FROM alpine

ARG APP_VERSION
ARG TARGETARCH

ENV APP_ENV=lite
ENV APP_VERSION=$APP_VERSION
ENV APP_SERVER_PORT=8080
ENV DOCKER_HOST=unix:///var/run/docker.sock
ENV STORAGE_LOCAL_PATH=/dpanel
ENV DB_DATABASE=${STORAGE_LOCAL_PATH}/dpanel.db

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && \
  apk add --no-cache --update musl libc6-compat docker-compose

COPY ./runtime/dpanel-${TARGETARCH} /app/server/dpanel
COPY ./runtime/config.yaml /app/server/config.yaml

WORKDIR /app
VOLUME [ "/dpanel" ]

EXPOSE 8080

ENTRYPOINT [ "sh", "-c", "/app/server/dpanel server:start -f /app/server/config.yaml" ]