// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q         = new(Query)
	Container *container
	RunEnv    *runEnv
	Site      *site
	Task      *task
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Container = &Q.Container
	RunEnv = &Q.RunEnv
	Site = &Q.Site
	Task = &Q.Task
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		Container: newContainer(db, opts...),
		RunEnv:    newRunEnv(db, opts...),
		Site:      newSite(db, opts...),
		Task:      newTask(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Container container
	RunEnv    runEnv
	Site      site
	Task      task
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Container: q.Container.clone(db),
		RunEnv:    q.RunEnv.clone(db),
		Site:      q.Site.clone(db),
		Task:      q.Task.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Container: q.Container.replaceDB(db),
		RunEnv:    q.RunEnv.replaceDB(db),
		Site:      q.Site.replaceDB(db),
		Task:      q.Task.replaceDB(db),
	}
}

type queryCtx struct {
	Container IContainerDo
	RunEnv    IRunEnvDo
	Site      ISiteDo
	Task      ITaskDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Container: q.Container.WithContext(ctx),
		RunEnv:    q.RunEnv.WithContext(ctx),
		Site:      q.Site.WithContext(ctx),
		Task:      q.Task.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
