// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q          = new(Query)
	Event      *event
	Image      *image
	Notice     *notice
	Registry   *registry
	RunEnv     *runEnv
	Site       *site
	SiteDomain *siteDomain
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Event = &Q.Event
	Image = &Q.Image
	Notice = &Q.Notice
	Registry = &Q.Registry
	RunEnv = &Q.RunEnv
	Site = &Q.Site
	SiteDomain = &Q.SiteDomain
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:         db,
		Event:      newEvent(db, opts...),
		Image:      newImage(db, opts...),
		Notice:     newNotice(db, opts...),
		Registry:   newRegistry(db, opts...),
		RunEnv:     newRunEnv(db, opts...),
		Site:       newSite(db, opts...),
		SiteDomain: newSiteDomain(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Event      event
	Image      image
	Notice     notice
	Registry   registry
	RunEnv     runEnv
	Site       site
	SiteDomain siteDomain
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		Event:      q.Event.clone(db),
		Image:      q.Image.clone(db),
		Notice:     q.Notice.clone(db),
		Registry:   q.Registry.clone(db),
		RunEnv:     q.RunEnv.clone(db),
		Site:       q.Site.clone(db),
		SiteDomain: q.SiteDomain.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		Event:      q.Event.replaceDB(db),
		Image:      q.Image.replaceDB(db),
		Notice:     q.Notice.replaceDB(db),
		Registry:   q.Registry.replaceDB(db),
		RunEnv:     q.RunEnv.replaceDB(db),
		Site:       q.Site.replaceDB(db),
		SiteDomain: q.SiteDomain.replaceDB(db),
	}
}

type queryCtx struct {
	Event      IEventDo
	Image      IImageDo
	Notice     INoticeDo
	Registry   IRegistryDo
	RunEnv     IRunEnvDo
	Site       ISiteDo
	SiteDomain ISiteDomainDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Event:      q.Event.WithContext(ctx),
		Image:      q.Image.WithContext(ctx),
		Notice:     q.Notice.WithContext(ctx),
		Registry:   q.Registry.WithContext(ctx),
		RunEnv:     q.RunEnv.WithContext(ctx),
		Site:       q.Site.WithContext(ctx),
		SiteDomain: q.SiteDomain.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
