// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/donknap/dpanel/common/entity"
)

func newSiteDomain(db *gorm.DB, opts ...gen.DOOption) siteDomain {
	_siteDomain := siteDomain{}

	_siteDomain.siteDomainDo.UseDB(db, opts...)
	_siteDomain.siteDomainDo.UseModel(&entity.SiteDomain{})

	tableName := _siteDomain.siteDomainDo.TableName()
	_siteDomain.ALL = field.NewAsterisk(tableName)
	_siteDomain.ID = field.NewInt32(tableName, "id")
	_siteDomain.ContainerID = field.NewString(tableName, "container_id")
	_siteDomain.ServerName = field.NewString(tableName, "server_name")
	_siteDomain.Setting = field.NewField(tableName, "setting")
	_siteDomain.CreatedAt = field.NewTime(tableName, "created_at")

	_siteDomain.fillFieldMap()

	return _siteDomain
}

type siteDomain struct {
	siteDomainDo

	ALL         field.Asterisk
	ID          field.Int32
	ContainerID field.String
	ServerName  field.String
	Setting     field.Field
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (s siteDomain) Table(newTableName string) *siteDomain {
	s.siteDomainDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s siteDomain) As(alias string) *siteDomain {
	s.siteDomainDo.DO = *(s.siteDomainDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *siteDomain) updateTableName(table string) *siteDomain {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.ContainerID = field.NewString(table, "container_id")
	s.ServerName = field.NewString(table, "server_name")
	s.Setting = field.NewField(table, "setting")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *siteDomain) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *siteDomain) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id"] = s.ID
	s.fieldMap["container_id"] = s.ContainerID
	s.fieldMap["server_name"] = s.ServerName
	s.fieldMap["setting"] = s.Setting
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s siteDomain) clone(db *gorm.DB) siteDomain {
	s.siteDomainDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s siteDomain) replaceDB(db *gorm.DB) siteDomain {
	s.siteDomainDo.ReplaceDB(db)
	return s
}

type siteDomainDo struct{ gen.DO }

type ISiteDomainDo interface {
	gen.SubQuery
	Debug() ISiteDomainDo
	WithContext(ctx context.Context) ISiteDomainDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISiteDomainDo
	WriteDB() ISiteDomainDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISiteDomainDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISiteDomainDo
	Not(conds ...gen.Condition) ISiteDomainDo
	Or(conds ...gen.Condition) ISiteDomainDo
	Select(conds ...field.Expr) ISiteDomainDo
	Where(conds ...gen.Condition) ISiteDomainDo
	Order(conds ...field.Expr) ISiteDomainDo
	Distinct(cols ...field.Expr) ISiteDomainDo
	Omit(cols ...field.Expr) ISiteDomainDo
	Join(table schema.Tabler, on ...field.Expr) ISiteDomainDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISiteDomainDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISiteDomainDo
	Group(cols ...field.Expr) ISiteDomainDo
	Having(conds ...gen.Condition) ISiteDomainDo
	Limit(limit int) ISiteDomainDo
	Offset(offset int) ISiteDomainDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISiteDomainDo
	Unscoped() ISiteDomainDo
	Create(values ...*entity.SiteDomain) error
	CreateInBatches(values []*entity.SiteDomain, batchSize int) error
	Save(values ...*entity.SiteDomain) error
	First() (*entity.SiteDomain, error)
	Take() (*entity.SiteDomain, error)
	Last() (*entity.SiteDomain, error)
	Find() ([]*entity.SiteDomain, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SiteDomain, err error)
	FindInBatches(result *[]*entity.SiteDomain, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.SiteDomain) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISiteDomainDo
	Assign(attrs ...field.AssignExpr) ISiteDomainDo
	Joins(fields ...field.RelationField) ISiteDomainDo
	Preload(fields ...field.RelationField) ISiteDomainDo
	FirstOrInit() (*entity.SiteDomain, error)
	FirstOrCreate() (*entity.SiteDomain, error)
	FindByPage(offset int, limit int) (result []*entity.SiteDomain, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISiteDomainDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s siteDomainDo) Debug() ISiteDomainDo {
	return s.withDO(s.DO.Debug())
}

func (s siteDomainDo) WithContext(ctx context.Context) ISiteDomainDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s siteDomainDo) ReadDB() ISiteDomainDo {
	return s.Clauses(dbresolver.Read)
}

func (s siteDomainDo) WriteDB() ISiteDomainDo {
	return s.Clauses(dbresolver.Write)
}

func (s siteDomainDo) Session(config *gorm.Session) ISiteDomainDo {
	return s.withDO(s.DO.Session(config))
}

func (s siteDomainDo) Clauses(conds ...clause.Expression) ISiteDomainDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s siteDomainDo) Returning(value interface{}, columns ...string) ISiteDomainDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s siteDomainDo) Not(conds ...gen.Condition) ISiteDomainDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s siteDomainDo) Or(conds ...gen.Condition) ISiteDomainDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s siteDomainDo) Select(conds ...field.Expr) ISiteDomainDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s siteDomainDo) Where(conds ...gen.Condition) ISiteDomainDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s siteDomainDo) Order(conds ...field.Expr) ISiteDomainDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s siteDomainDo) Distinct(cols ...field.Expr) ISiteDomainDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s siteDomainDo) Omit(cols ...field.Expr) ISiteDomainDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s siteDomainDo) Join(table schema.Tabler, on ...field.Expr) ISiteDomainDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s siteDomainDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISiteDomainDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s siteDomainDo) RightJoin(table schema.Tabler, on ...field.Expr) ISiteDomainDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s siteDomainDo) Group(cols ...field.Expr) ISiteDomainDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s siteDomainDo) Having(conds ...gen.Condition) ISiteDomainDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s siteDomainDo) Limit(limit int) ISiteDomainDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s siteDomainDo) Offset(offset int) ISiteDomainDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s siteDomainDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISiteDomainDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s siteDomainDo) Unscoped() ISiteDomainDo {
	return s.withDO(s.DO.Unscoped())
}

func (s siteDomainDo) Create(values ...*entity.SiteDomain) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s siteDomainDo) CreateInBatches(values []*entity.SiteDomain, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s siteDomainDo) Save(values ...*entity.SiteDomain) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s siteDomainDo) First() (*entity.SiteDomain, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteDomain), nil
	}
}

func (s siteDomainDo) Take() (*entity.SiteDomain, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteDomain), nil
	}
}

func (s siteDomainDo) Last() (*entity.SiteDomain, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteDomain), nil
	}
}

func (s siteDomainDo) Find() ([]*entity.SiteDomain, error) {
	result, err := s.DO.Find()
	return result.([]*entity.SiteDomain), err
}

func (s siteDomainDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SiteDomain, err error) {
	buf := make([]*entity.SiteDomain, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s siteDomainDo) FindInBatches(result *[]*entity.SiteDomain, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s siteDomainDo) Attrs(attrs ...field.AssignExpr) ISiteDomainDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s siteDomainDo) Assign(attrs ...field.AssignExpr) ISiteDomainDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s siteDomainDo) Joins(fields ...field.RelationField) ISiteDomainDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s siteDomainDo) Preload(fields ...field.RelationField) ISiteDomainDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s siteDomainDo) FirstOrInit() (*entity.SiteDomain, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteDomain), nil
	}
}

func (s siteDomainDo) FirstOrCreate() (*entity.SiteDomain, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteDomain), nil
	}
}

func (s siteDomainDo) FindByPage(offset int, limit int) (result []*entity.SiteDomain, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s siteDomainDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s siteDomainDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s siteDomainDo) Delete(models ...*entity.SiteDomain) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *siteDomainDo) withDO(do gen.Dao) *siteDomainDo {
	s.DO = *do.(*gen.DO)
	return s
}
