// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/donknap/dpanel/common/entity"
)

func newSiteUpgrade(db *gorm.DB, opts ...gen.DOOption) siteUpgrade {
	_siteUpgrade := siteUpgrade{}

	_siteUpgrade.siteUpgradeDo.UseDB(db, opts...)
	_siteUpgrade.siteUpgradeDo.UseModel(&entity.SiteUpgrade{})

	tableName := _siteUpgrade.siteUpgradeDo.TableName()
	_siteUpgrade.ALL = field.NewAsterisk(tableName)
	_siteUpgrade.ID = field.NewInt32(tableName, "id")
	_siteUpgrade.Title = field.NewString(tableName, "title")
	_siteUpgrade.Status = field.NewInt32(tableName, "status")
	_siteUpgrade.Setting = field.NewField(tableName, "setting")
	_siteUpgrade.Logs = field.NewField(tableName, "logs")

	_siteUpgrade.fillFieldMap()

	return _siteUpgrade
}

type siteUpgrade struct {
	siteUpgradeDo

	ALL     field.Asterisk
	ID      field.Int32
	Title   field.String
	Status  field.Int32
	Setting field.Field
	Logs    field.Field

	fieldMap map[string]field.Expr
}

func (s siteUpgrade) Table(newTableName string) *siteUpgrade {
	s.siteUpgradeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s siteUpgrade) As(alias string) *siteUpgrade {
	s.siteUpgradeDo.DO = *(s.siteUpgradeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *siteUpgrade) updateTableName(table string) *siteUpgrade {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.Title = field.NewString(table, "title")
	s.Status = field.NewInt32(table, "status")
	s.Setting = field.NewField(table, "setting")
	s.Logs = field.NewField(table, "logs")

	s.fillFieldMap()

	return s
}

func (s *siteUpgrade) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *siteUpgrade) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id"] = s.ID
	s.fieldMap["title"] = s.Title
	s.fieldMap["status"] = s.Status
	s.fieldMap["setting"] = s.Setting
	s.fieldMap["logs"] = s.Logs
}

func (s siteUpgrade) clone(db *gorm.DB) siteUpgrade {
	s.siteUpgradeDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s siteUpgrade) replaceDB(db *gorm.DB) siteUpgrade {
	s.siteUpgradeDo.ReplaceDB(db)
	return s
}

type siteUpgradeDo struct{ gen.DO }

type ISiteUpgradeDo interface {
	gen.SubQuery
	Debug() ISiteUpgradeDo
	WithContext(ctx context.Context) ISiteUpgradeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISiteUpgradeDo
	WriteDB() ISiteUpgradeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISiteUpgradeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISiteUpgradeDo
	Not(conds ...gen.Condition) ISiteUpgradeDo
	Or(conds ...gen.Condition) ISiteUpgradeDo
	Select(conds ...field.Expr) ISiteUpgradeDo
	Where(conds ...gen.Condition) ISiteUpgradeDo
	Order(conds ...field.Expr) ISiteUpgradeDo
	Distinct(cols ...field.Expr) ISiteUpgradeDo
	Omit(cols ...field.Expr) ISiteUpgradeDo
	Join(table schema.Tabler, on ...field.Expr) ISiteUpgradeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISiteUpgradeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISiteUpgradeDo
	Group(cols ...field.Expr) ISiteUpgradeDo
	Having(conds ...gen.Condition) ISiteUpgradeDo
	Limit(limit int) ISiteUpgradeDo
	Offset(offset int) ISiteUpgradeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISiteUpgradeDo
	Unscoped() ISiteUpgradeDo
	Create(values ...*entity.SiteUpgrade) error
	CreateInBatches(values []*entity.SiteUpgrade, batchSize int) error
	Save(values ...*entity.SiteUpgrade) error
	First() (*entity.SiteUpgrade, error)
	Take() (*entity.SiteUpgrade, error)
	Last() (*entity.SiteUpgrade, error)
	Find() ([]*entity.SiteUpgrade, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SiteUpgrade, err error)
	FindInBatches(result *[]*entity.SiteUpgrade, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.SiteUpgrade) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISiteUpgradeDo
	Assign(attrs ...field.AssignExpr) ISiteUpgradeDo
	Joins(fields ...field.RelationField) ISiteUpgradeDo
	Preload(fields ...field.RelationField) ISiteUpgradeDo
	FirstOrInit() (*entity.SiteUpgrade, error)
	FirstOrCreate() (*entity.SiteUpgrade, error)
	FindByPage(offset int, limit int) (result []*entity.SiteUpgrade, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISiteUpgradeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s siteUpgradeDo) Debug() ISiteUpgradeDo {
	return s.withDO(s.DO.Debug())
}

func (s siteUpgradeDo) WithContext(ctx context.Context) ISiteUpgradeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s siteUpgradeDo) ReadDB() ISiteUpgradeDo {
	return s.Clauses(dbresolver.Read)
}

func (s siteUpgradeDo) WriteDB() ISiteUpgradeDo {
	return s.Clauses(dbresolver.Write)
}

func (s siteUpgradeDo) Session(config *gorm.Session) ISiteUpgradeDo {
	return s.withDO(s.DO.Session(config))
}

func (s siteUpgradeDo) Clauses(conds ...clause.Expression) ISiteUpgradeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s siteUpgradeDo) Returning(value interface{}, columns ...string) ISiteUpgradeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s siteUpgradeDo) Not(conds ...gen.Condition) ISiteUpgradeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s siteUpgradeDo) Or(conds ...gen.Condition) ISiteUpgradeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s siteUpgradeDo) Select(conds ...field.Expr) ISiteUpgradeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s siteUpgradeDo) Where(conds ...gen.Condition) ISiteUpgradeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s siteUpgradeDo) Order(conds ...field.Expr) ISiteUpgradeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s siteUpgradeDo) Distinct(cols ...field.Expr) ISiteUpgradeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s siteUpgradeDo) Omit(cols ...field.Expr) ISiteUpgradeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s siteUpgradeDo) Join(table schema.Tabler, on ...field.Expr) ISiteUpgradeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s siteUpgradeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISiteUpgradeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s siteUpgradeDo) RightJoin(table schema.Tabler, on ...field.Expr) ISiteUpgradeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s siteUpgradeDo) Group(cols ...field.Expr) ISiteUpgradeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s siteUpgradeDo) Having(conds ...gen.Condition) ISiteUpgradeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s siteUpgradeDo) Limit(limit int) ISiteUpgradeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s siteUpgradeDo) Offset(offset int) ISiteUpgradeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s siteUpgradeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISiteUpgradeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s siteUpgradeDo) Unscoped() ISiteUpgradeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s siteUpgradeDo) Create(values ...*entity.SiteUpgrade) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s siteUpgradeDo) CreateInBatches(values []*entity.SiteUpgrade, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s siteUpgradeDo) Save(values ...*entity.SiteUpgrade) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s siteUpgradeDo) First() (*entity.SiteUpgrade, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteUpgrade), nil
	}
}

func (s siteUpgradeDo) Take() (*entity.SiteUpgrade, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteUpgrade), nil
	}
}

func (s siteUpgradeDo) Last() (*entity.SiteUpgrade, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteUpgrade), nil
	}
}

func (s siteUpgradeDo) Find() ([]*entity.SiteUpgrade, error) {
	result, err := s.DO.Find()
	return result.([]*entity.SiteUpgrade), err
}

func (s siteUpgradeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SiteUpgrade, err error) {
	buf := make([]*entity.SiteUpgrade, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s siteUpgradeDo) FindInBatches(result *[]*entity.SiteUpgrade, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s siteUpgradeDo) Attrs(attrs ...field.AssignExpr) ISiteUpgradeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s siteUpgradeDo) Assign(attrs ...field.AssignExpr) ISiteUpgradeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s siteUpgradeDo) Joins(fields ...field.RelationField) ISiteUpgradeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s siteUpgradeDo) Preload(fields ...field.RelationField) ISiteUpgradeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s siteUpgradeDo) FirstOrInit() (*entity.SiteUpgrade, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteUpgrade), nil
	}
}

func (s siteUpgradeDo) FirstOrCreate() (*entity.SiteUpgrade, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteUpgrade), nil
	}
}

func (s siteUpgradeDo) FindByPage(offset int, limit int) (result []*entity.SiteUpgrade, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s siteUpgradeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s siteUpgradeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s siteUpgradeDo) Delete(models ...*entity.SiteUpgrade) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *siteUpgradeDo) withDO(do gen.Dao) *siteUpgradeDo {
	s.DO = *do.(*gen.DO)
	return s
}
