FROM dpanel/dpanel:lite-debian

ARG PROXY="proxy=0"
ENV APP_ENV=production

RUN apt-get update && apt-get install -y --no-install-recommends \
    nginx \
    openssl \
    curl && \
    mkdir -p /tmp/nginx/body /var/lib/nginx/cache/public /var/lib/nginx/cache/private /var/www/challenges && \
    export ${PROXY} && \
    curl https://raw.githubusercontent.com/acmesh-official/acme.sh/dev/acme.sh | sh -s -- --install-online --config-home /dpanel/acme && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/default.conf /etc/nginx/http.d/default.conf
COPY ./docker/nginx/include /etc/nginx/conf.d/include
COPY ./docker/task/entrypoint.sh /docker/entrypoint.sh

RUN chmod 755 /docker/entrypoint.sh

EXPOSE 80 443

WORKDIR /app/server

ENTRYPOINT [ "/docker/entrypoint.sh" ]