# syntax=docker/dockerfile:1
ARG LITE_FROM_BASE=dpanel/dpanel:lite-debian
ARG PROD_FROM_BASE=dpanel/dpanel:debian

FROM --platform=${BUILDPLATFORM} dpanel/builder:debian AS source

ARG HTTP_PROXY
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTP_PROXY}

RUN export HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTP_PROXY} && \
    apt-get update && apt-get install -y --no-install-recommends \
    make gcc libc6-dev git

ARG APP_VERSION
ARG REPO_BRANCH
ARG REPO_PULL

ENV APP_VERSION=${APP_VERSION}
ENV REPO_BRANCH=${REPO_BRANCH:-master}
ENV REPO_PULL=${REPO_PULL:-false}

WORKDIR /src

COPY . .

RUN --mount=type=secret,id=GIT_TOKEN \
    if [ "$REPO_PULL" = "true" ] || [ "$REPO_PULL" = "1" ]; then \
        echo ">> REPO_PULL enabled. Clearing local files and pulling from remote..." && \
        rm -rf ./* ./.[!.]* 2>/dev/null || true && \
        export GH_TOKEN=$(cat /run/secrets/GIT_TOKEN) && \
        gh repo clone donknap/dpanel . -- -b ${REPO_BRANCH} --depth 1 && \
        rm -rf ./app/pro && \
        gh repo clone donknap/dpanel-pro ./app/pro -- --depth 1; \
    else \
        echo ">> REPO_PULL disabled. Using local source code..." ; \
    fi && \
    go test -v --run TestGenerateDefines ./app/pro/tests/obfuscate_test.go

FROM --platform=${BUILDPLATFORM} dpanel/builder:debian AS builder

ARG HTTP_PROXY
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTP_PROXY}

RUN export HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTP_PROXY} && \
    apt-get update && apt-get install -y --no-install-recommends \
    make gcc libc6-dev git && \
    go install mvdan.cc/garble@latest

ARG APP_VERSION
ARG TARGETARCH
ENV APP_VERSION=${APP_VERSION}

WORKDIR /src

COPY --from=source /src /src

RUN --mount=type=secret,id=GARBLE_SEED \
    --mount=type=cache,target=/root/.cache/go-build,id=dpanel_go_build_${TARGETARCH} \
    --mount=type=cache,target=/go/pkg/mod,id=dpanel_mod_cache_${TARGETARCH} \
    export SEED=$(cat /run/secrets/GARBLE_SEED) && \
    export HTTP_PROXY=${HTTP_PROXY} && \
    export HTTPS_PROXY=${HTTP_PROXY} && \
    COMMON_ARGS="VERSION=${APP_VERSION} FAMILY=${APP_FAMILY-pe} OS=linux GNU=1 GARBLE=1 GARBLE_SEED=${SEED}" && \
    if [ "$TARGETARCH" = "amd64" ]; then \
        make build ${COMMON_ARGS} AMD64=1 AMD64_CC=gcc; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        make build ${COMMON_ARGS} ARM64=1 ARM64_CC=$TC_GNU_ARM64; \
    elif [ "$TARGETARCH" = "arm" ]; then \
        make build ${COMMON_ARGS} ARM7=1 ARM7_CC=$TC_GNU_ARMV7; \
    else \
        echo "Unsupported architecture: $TARGETARCH" && exit 1; \
    fi

FROM scratch AS binary-export
COPY --from=builder /src/runtime /

FROM $LITE_FROM_BASE AS lite

ARG APP_FAMILY
ARG APP_VERSION
ARG TARGETARCH

ENV APP_VERSION=$APP_VERSION
ENV APP_FAMILY=$APP_FAMILY

COPY --from=builder /src/runtime/dpanel${APP_FAMILY:+"-${APP_FAMILY}"}-gnu-${TARGETARCH} /app/server/dpanel

FROM $PROD_FROM_BASE AS production

ARG APP_FAMILY
ARG APP_VERSION
ARG TARGETARCH

ENV APP_VERSION=$APP_VERSION
ENV APP_FAMILY=$APP_FAMILY

COPY --from=builder /src/runtime/dpanel${APP_FAMILY:+"-${APP_FAMILY}"}-gnu-${TARGETARCH} /app/server/dpanel