FROM --platform=${BUILDPLATFORM} golang:1.25-bookworm AS builder

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG APP_VERSION
ARG HTTP_PROXY

WORKDIR /src

COPY app/agent/go.mod app/agent/go.sum ./
RUN export HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTP_PROXY} && go mod download

COPY app/agent ./

RUN if [ "${TARGETARCH}" = "arm" ]; then export GOARM="${TARGETVARIANT#v}"; fi && \
    GOTOOLCHAIN=local CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -trimpath -ldflags="-s -w -X 'main.version=${APP_VERSION}'" -o /agent .

FROM scratch

COPY --from=builder /agent /agent

WORKDIR /

LABEL com.dpanel.container.title=DPanel-文件管理助手

ENTRYPOINT ["/agent"]
