ARG LIBC=gnu
ARG VERSION=12.3
ARG TARGETARCH

FROM --platform=${BUILDPLATFORM} dpanel/builder:${TARGETARCH}-${LIBC}-${VERSION} AS toolchain
FROM --platform=${BUILDPLATFORM} golang:1.25-bookworm AS builder

ARG HTTP_PROXY

RUN export HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTP_PROXY} && \
    apt-get update && apt-get install -y --no-install-recommends make git

WORKDIR /src

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod,id=dpanel_mod_cache \
    export HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTP_PROXY} && \
    go mod download

COPY ./ /src

ARG TARGETARCH
ARG APP_VERSION
ARG APP_FAMILY

RUN --mount=type=cache,target=/root/.cache/go-build,id=dpanel_go_build_${TARGETARCH} \
    --mount=type=cache,target=/go/pkg/mod,id=dpanel_mod_cache_${TARGETARCH} \
    --mount=type=bind,from=toolchain,source=/toolchains,target=/toolchains \
    export HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTP_PROXY} && \
    COMMON_ARGS="VERSION=${APP_VERSION} FAMILY=${APP_FAMILY-ce} OS=linux LIBC=gnu" && \
    if [ "$TARGETARCH" = "amd64" ]; then \
        export CC=$(echo /toolchains/*amd64-gnu-*/bin/*-gcc); \
        make build ${COMMON_ARGS} AMD64=1 ARM64=0 ARMV7=0 CC_AMD64=$CC; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        export CC=$(echo /toolchains/*arm64-gnu-*/bin/*-gcc); \
        make build ${COMMON_ARGS} AMD64=0 ARM64=1 ARMV7=0 CC_ARM64=$CC; \
    elif [ "$TARGETARCH" = "arm" ]; then \
        export CC=$(echo /toolchains/*arm-gnu-*/bin/*-gcc); \
        make build ${COMMON_ARGS} AMD64=0 ARM64=0 ARMV7=1 CC_ARMV7=$CC; \
    fi

FROM scratch AS binary-export
COPY --from=builder /src/runtime /

FROM debian:bookworm-slim AS base

ARG HTTP_PROXY

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache && \
    sed -i 's/deb.debian111.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/debian.sources && \
    export HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTP_PROXY} && \
    apt-get update && apt-get install -y --no-install-recommends \
    tzdata git curl ca-certificates gnupg openssh-client iputils-ping && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && apt-get install -y --no-install-recommends docker-ce-cli docker-compose-plugin docker-buildx-plugin && \
    rm -f /usr/bin/docker-compose && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    mkdir -p /root/.ssh && chmod 700 /root/.ssh

WORKDIR /app/server
VOLUME [ "/dpanel" ]

FROM base AS lite

ARG TARGETARCH
ARG APP_VERSION
ARG APP_FAMILY

ENV TZ=Asia/Shanghai
ENV PATH="/app/server:${PATH}"
ENV DOCKER_HOST=unix:///var/run/docker.sock

ENV DP_SYSTEM_STORAGE_LOCAL_PATH=/dpanel
ENV DP_DB_DATABASE=${DP_SYSTEM_STORAGE_LOCAL_PATH}/dpanel.db
ENV DP_ACME_CONFIG_HOME=/dpanel/acme
ENV DP_RUN_IN_CONTAINER=1

# 兼容旧的环境变量
ENV APP_NAME=dpanel
ENV APP_SERVER_PORT=8080
ENV APP_VERSION=$APP_VERSION
ENV APP_FAMILY=$APP_FAMILY
ENV STORAGE_LOCAL_PATH=$DP_SYSTEM_STORAGE_LOCAL_PATH
ENV DB_DATABASE=$DP_DB_DATABASE
ENV APP_ENV=lite

COPY --from=builder /src/runtime/dpanel${APP_FAMILY:+"-${APP_FAMILY}"}-gnu-${TARGETARCH} /app/server/dpanel
COPY ./config.yaml /app/server/config.yaml
COPY ./docker/script /app/script
COPY ./docker/task /docker

RUN chmod -R 755 /docker/* /app/server/dpanel

EXPOSE 8080

ENTRYPOINT [ "/docker/entrypoint-lite.sh" ]

FROM base AS production

ARG HTTP_PROXY

COPY ./docker/task /docker

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    export HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTP_PROXY} && \
    printf '#!/bin/sh\nexit 101' > /usr/sbin/policy-rc.d && chmod +x /usr/sbin/policy-rc.d && \
    apt-get update && apt-get install -y --no-install-recommends nginx cron && \
    id -u nginx >/dev/null 2>&1 || (groupadd -r nginx && useradd -r -g nginx -s /sbin/nologin nginx) && \
    rm /usr/sbin/policy-rc.d && \
    mkdir -p /tmp/nginx/body /var/lib/nginx/cache/public /var/lib/nginx/cache/private /var/www/challenges && \
    tar -zxvf /docker/acme.tar.gz -C /docker && cd /docker/acme.sh-master && ./acme.sh --install --config-home /dpanel/acme

ARG TARGETARCH
ARG APP_VERSION
ARG APP_FAMILY

ENV TZ=Asia/Shanghai
ENV PATH="/app/server:${PATH}"
ENV DOCKER_HOST=unix:///var/run/docker.sock

ENV DP_SYSTEM_STORAGE_LOCAL_PATH=/dpanel
ENV DP_DB_DATABASE=${DP_SYSTEM_STORAGE_LOCAL_PATH}/dpanel.db
ENV DP_ACME_CONFIG_HOME=/dpanel/acme
ENV DP_RUN_IN_CONTAINER=1

# 兼容旧的环境变量
ENV APP_NAME=dpanel
ENV APP_SERVER_PORT=8080
ENV APP_VERSION=$APP_VERSION
ENV APP_FAMILY=$APP_FAMILY
ENV STORAGE_LOCAL_PATH=$DP_SYSTEM_STORAGE_LOCAL_PATH
ENV DB_DATABASE=$DP_DB_DATABASE
ENV APP_ENV=production

COPY --from=builder /src/runtime/dpanel${APP_FAMILY:+"-${APP_FAMILY}"}-gnu-${TARGETARCH} /app/server/dpanel
COPY ./config.yaml /app/server/config.yaml
COPY ./docker/script /app/script
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/default.conf /etc/nginx/sites-enabled/default
COPY ./docker/nginx/include /etc/nginx/conf.d/include

RUN chmod -R 755 /docker/* /app/server/dpanel

EXPOSE 443 80 8080
ENTRYPOINT [ "/docker/entrypoint.sh" ]