FROM debian:bookworm-slim AS base

ARG TARGETARCH
ARG APP_VERSION
ARG APP_FAMILY
ARG HTTP_PROXY

ENV TZ=Asia/Shanghai
ENV PATH="/app/server:${PATH}"
ENV DOCKER_HOST=unix:///var/run/docker.sock
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTP_PROXY}

ENV DP_SYSTEM_STORAGE_LOCAL_PATH=/dpanel
ENV DP_DB_DATABASE=${DP_SYSTEM_STORAGE_LOCAL_PATH}/dpanel.db
ENV DP_ACME_CONFIG_HOME=/dpanel/acme

# 兼容旧的环境变量
ENV APP_NAME=dpanel
ENV APP_SERVER_PORT=8080
ENV APP_VERSION=$APP_VERSION
ENV APP_FAMILY=$APP_FAMILY
ENV STORAGE_LOCAL_PATH=$DP_SYSTEM_STORAGE_LOCAL_PATH
ENV DB_DATABASE=$DP_DB_DATABASE

COPY ./runtime/dpanel${APP_FAMILY:+"-${APP_FAMILY}"}-gnu-${TARGETARCH} /app/server/dpanel
COPY ./config.yaml /app/server/config.yaml
COPY ./docker/script /app/script
COPY ./docker/task /docker

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    sed -i 's/deb.debian111.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && apt-get install -y --no-install-recommends \
    tzdata git curl ca-certificates gnupg openssh-client iputils-ping && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && apt-get install -y --no-install-recommends docker-ce-cli docker-compose-plugin docker-buildx-plugin && \
    rm -f /usr/bin/docker-compose && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    mkdir -p /root/.ssh && chmod 700 /root/.ssh && chmod -R 755 /docker/* /app/server/dpanel

WORKDIR /app/server
EXPOSE 8080
VOLUME [ "/dpanel" ]

FROM base AS lite
ENV APP_ENV=lite

ENTRYPOINT [ "/docker/entrypoint-lite.sh" ]

FROM base AS production

ENV APP_ENV=production

COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/default.conf /etc/nginx/sites-enabled/default
COPY ./docker/nginx/include /etc/nginx/conf.d/include

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    printf '#!/bin/sh\nexit 101' > /usr/sbin/policy-rc.d && chmod +x /usr/sbin/policy-rc.d && \
    apt-get update && apt-get install -y --no-install-recommends nginx cron && \
    id -u nginx >/dev/null 2>&1 || (groupadd -r nginx && useradd -r -g nginx -s /sbin/nologin nginx) && \
    rm /usr/sbin/policy-rc.d && \
    mkdir -p /tmp/nginx/body /var/lib/nginx/cache/public /var/lib/nginx/cache/private /var/www/challenges && \
    tar -zxvf /docker/acme.tar.gz -C /docker && cd /docker/acme.sh-master && ./acme.sh --install --config-home /dpanel/acme

EXPOSE 443 80 8080
ENTRYPOINT [ "/docker/entrypoint.sh" ]