package compose

import (
	"github.com/compose-spec/compose-go/v2/types"
	"os"
	"path/filepath"
)

func NewComposeWithYaml(yaml []byte) (*Wrapper, error) {
	tempComposeFile, _ := os.CreateTemp("", "dpanel-compose")
	err := os.WriteFile(
		tempComposeFile.Name(),
		append([]byte("# 此文件由 dpanel 面板生成，请勿修改！ \n# Generated by dpanel, do not modify!\n"), yaml...),
		0666,
	)
	defer os.Remove(tempComposeFile.Name())

	if err != nil {
		return nil, err
	}
	wrapper, err := NewCompose(WithYamlPath(tempComposeFile.Name()))
	if err != nil {
		return nil, err
	}
	return wrapper, nil
}

type Wrapper struct {
	Project *types.Project
}

// 区别于 Project.GetService 方法，此方法会将扩展信息一起返回
func (self Wrapper) GetService(name string) (types.ServiceConfig, ExtService, error) {
	service, err := self.Project.GetService(name)
	if err != nil {
		return types.ServiceConfig{}, ExtService{}, err
	}

	ext := ExtService{}
	exists, err := service.Extensions.Get(ExtensionServiceName, &ext)
	if err == nil && exists {
		return service, ext, nil
	}
	return service, ExtService{}, nil
}

func (self Wrapper) GetBaseCommand() []string {
	cmd := make([]string, 0)
	for _, file := range self.Project.ComposeFiles {
		cmd = append(cmd, "-f", file)
	}
	cmd = append(cmd, "-p", self.Project.Name)
	for _, envFileName := range []string{
		".env", ".dpanel.env",
	} {
		envFilePath := filepath.Join(self.Project.WorkingDir, envFileName)
		_, err := os.Stat(envFilePath)
		if err == nil {
			cmd = append(cmd, "--env-file", envFilePath)
		}
	}
	return cmd
}
