// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameNotice = "ims_notice"

// Notice mapped from table <ims_notice>
type Notice struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	Type      string    `gorm:"column:type" json:"type"`
	Title     string    `gorm:"column:title" json:"title"`
	Message   string    `gorm:"column:message" json:"message"`
	CreatedAt time.Time `gorm:"column:created_at" json:"createdAt"`
}

// TableName Notice's table name
func (*Notice) TableName() string {
	return TableNameNotice
}
