// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"github.com/donknap/dpanel/common/accessor"
)

const TableNameUserPermission = "ims_user_permission"

// UserPermission mapped from table <ims_user_permission>
type UserPermission struct {
	ID       int32                           `gorm:"column:id;primaryKey" json:"id"`
	Username string                          `gorm:"column:username" json:"username"`
	Value    *accessor.PermissionValueOption `gorm:"column:value;serializer:json" json:"value"`
}

// TableName UserPermission's table name
func (*UserPermission) TableName() string {
	return TableNameUserPermission
}
