// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameEvent = "ims_event"

// Event mapped from table <ims_event>
type Event struct {
	ID        int32  `gorm:"column:id;type:INTEGER" json:"id"`
	Type      string `gorm:"column:type" json:"type"`
	Action    string `gorm:"column:action" json:"action"`
	Message   string `gorm:"column:message" json:"message"`
	CreatedAt string `gorm:"column:created_at" json:"createdAt"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
