// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"github.com/donknap/dpanel/common/accessor"
)

const TableNameCompose = "ims_compose"

// Compose mapped from table <ims_compose>
type Compose struct {
	ID      int32                          `gorm:"column:id;primaryKey" json:"id"`
	Name    string                         `gorm:"column:name" json:"name"`
	Title   string                         `gorm:"column:title" json:"title"`
	Setting *accessor.ComposeSettingOption `gorm:"column:setting;serializer:json" json:"setting"`
}

// TableName Compose's table name
func (*Compose) TableName() string {
	return TableNameCompose
}
