// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"github.com/donknap/dpanel/common/accessor"
)

const TableNameCron = "ims_cron"

// Cron mapped from table <ims_cron>
type Cron struct {
	ID      int32                       `gorm:"column:id;type:INTEGER" json:"id"`
	Title   string                      `gorm:"column:title" json:"title"`
	Setting *accessor.CronSettingOption `gorm:"column:setting;serializer:json" json:"setting"`
}

// TableName Cron's table name
func (*Cron) TableName() string {
	return TableNameCron
}
