// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSite = "ims_site"

// Site mapped from table <ims_site>
type Site struct {
	ID          int32      `gorm:"column:id;type:INTEGER" json:"id"`
	SiteID      string     `gorm:"column:site_id;type:text" json:"siteId"`
	SiteName    string     `gorm:"column:site_name;type:text" json:"siteName"`
	SiteURL     string     `gorm:"column:site_url;type:text" json:"siteUrl"`
	ContainerID int32      `gorm:"column:container_id;type:integer" json:"containerId"`
	Container   *Container `gorm:"foreignKey:container_id" json:"container"`
}

// TableName Site's table name
func (*Site) TableName() string {
	return TableNameSite
}
