// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"github.com/donknap/dpanel/common/accessor"
	"gorm.io/gorm"
)

const TableNameSite = "ims_site"

// Site mapped from table <ims_site>
type Site struct {
	ID            int32                             `gorm:"column:id;type:INTEGER" json:"id"`
	SiteTitle     string                            `gorm:"column:site_title" json:"siteTitle"`
	SiteName      string                            `gorm:"column:site_name" json:"siteName"`
	SiteURL       string                            `gorm:"column:site_url" json:"siteUrl"`
	SiteURLExt    *accessor.SiteUrlExtOption        `gorm:"column:site_url_ext;serializer:json" json:"siteUrlExt"`
	Env           *accessor.SiteEnvOption           `gorm:"column:env;serializer:json" json:"env"`
	Type          int32                             `gorm:"column:type" json:"type"`
	ContainerInfo *accessor.SiteContainerInfoOption `gorm:"column:container_info" json:"containerInfo"`
	Status        int32                             `gorm:"column:status" json:"status"`
	StatusStep    string                            `gorm:"column:status_step" json:"statusStep"`
	Message       string                            `gorm:"column:message" json:"message"`
	DeletedAt     gorm.DeletedAt                    `gorm:"column:deleted_at" json:"deletedAt"`
}

// TableName Site's table name
func (*Site) TableName() string {
	return TableNameSite
}
