// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"github.com/donknap/dpanel/common/accessor"
)

const TableNameRegistry = "ims_registry"

// Registry mapped from table <ims_registry>
type Registry struct {
	ID            int32                           `gorm:"column:id;primaryKey" json:"id"`
	Title         string                          `gorm:"column:title" json:"title"`
	ServerAddress string                          `gorm:"column:server_address" json:"serverAddress"`
	Setting       *accessor.RegistrySettingOption `gorm:"column:setting;serializer:json" json:"setting"`
}

// TableName Registry's table name
func (*Registry) TableName() string {
	return TableNameRegistry
}
