// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameTask = "ims_task"

// Task mapped from table <ims_task>
type Task struct {
	ID      int32  `gorm:"column:id;type:INTEGER" json:"id"`
	TaskID  int32  `gorm:"column:task_id" json:"taskId"`
	Status  int32  `gorm:"column:status" json:"status"`
	Message string `gorm:"column:message" json:"message"`
	Step    string `gorm:"column:step" json:"step"`
	Type    string `gorm:"column:type" json:"type"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
