// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"github.com/donknap/dpanel/common/accessor"
	"gorm.io/gorm"
)

const TableNameImage = "ims_image"

// Image mapped from table <ims_image>
type Image struct {
	ID             int32                    `gorm:"column:id;type:INTEGER" json:"id"`
	Name           string                   `gorm:"column:name" json:"name"`
	Md5            string                   `gorm:"column:md5" json:"md5"`
	Tag            *accessor.ImageTagOption `gorm:"column:tag;serializer:json" json:"tag"`
	Size           string                   `gorm:"column:size" json:"size"`
	BuildGit       string                   `gorm:"column:build_git" json:"buildGit"`
	Registry       string                   `gorm:"column:registry" json:"registry"`
	Status         int32                    `gorm:"column:status" json:"status"`
	StatusStep     string                   `gorm:"column:status_step" json:"statusStep"`
	Message        string                   `gorm:"column:message" json:"message"`
	CreatedAt      int32                    `gorm:"column:created_at" json:"createdAt"`
	DeletedAt      gorm.DeletedAt           `gorm:"column:deleted_at" json:"deletedAt"`
	ContainerTotal int32                    `gorm:"column:container_total" json:"containerTotal"`
	Type           int32                    `gorm:"column:type" json:"type"`
}

// TableName Image's table name
func (*Image) TableName() string {
	return TableNameImage
}
