// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameRunEnv = "ims_run_env"

// RunEnv mapped from table <ims_run_env>
type RunEnv struct {
	ID         int32  `gorm:"column:id;type:INTEGER" json:"id"`
	Name       string `gorm:"column:name;type:TEXT" json:"name"`
	Lang       string `gorm:"column:lang;type:TEXT" json:"lang"`
	ImageBase  string `gorm:"column:image_base;type:TEXT" json:"imageBase"`
	Extra1     string `gorm:"column:extra_1;type:TEXT" json:"extra1"`
	Extra2     string `gorm:"column:extra_2;type:text" json:"extra2"`
	Extra3     string `gorm:"column:extra_3;type:text" json:"extra3"`
	ColumnName int32  `gorm:"column:column_name;type:integer" json:"columnName"`
}

// TableName RunEnv's table name
func (*RunEnv) TableName() string {
	return TableNameRunEnv
}
