// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameContainer = "ims_container"

// Container mapped from table <ims_container>
type Container struct {
	ID     int32  `gorm:"column:id;type:INTEGER" json:"id"`
	Image  string `gorm:"column:image;type:text" json:"image"`
	Params string `gorm:"column:params;type:text" json:"params"`
	Status int32  `gorm:"column:status;type:integer" json:"status"`
}

// TableName Container's table name
func (*Container) TableName() string {
	return TableNameContainer
}
