// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"github.com/donknap/dpanel/common/accessor"
)

const TableNameStore = "ims_store"

// Store mapped from table <ims_store>
type Store struct {
	ID      int32                        `gorm:"column:id;type:INTEGER" json:"id"`
	Title   string                       `gorm:"column:title" json:"title"`
	Name    string                       `gorm:"column:name" json:"name"`
	Setting *accessor.StoreSettingOption `gorm:"column:setting;serializer:json" json:"setting"`
}

// TableName Store's table name
func (*Store) TableName() string {
	return TableNameStore
}
