// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameContainer = "ims_container"

// Container mapped from table <ims_container>
type Container struct {
	ID         int32  `gorm:"column:id;type:INTEGER" json:"id"`
	Image      string `gorm:"column:image" json:"image"`
	Dockerfile string `gorm:"column:dockerfile" json:"dockerfile"`
	Status     int32  `gorm:"column:status" json:"status"`
	Version    string `gorm:"column:version" json:"version"`
}

// TableName Container's table name
func (*Container) TableName() string {
	return TableNameContainer
}
