name: Parallel Download DPanel Resources

on:
  workflow_dispatch:

jobs:
  download-gnu:
    runs-on: ubuntu-latest
    steps:
      - name: Download GNU
        run: |
          mkdir -p artifacts
          cd artifacts
          # GNU 12
          curl -SLO https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
          curl -SLO https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz
          curl -SL -o x86_64-gnu-toolchain-12.3.tar.bz2 https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--glibc--stable-2023.08-1.tar.bz2
          # GNU 13
          curl -SLO https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
          curl -SLO https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz
          curl -SL -o x86_64-gnu-toolchain-13.2.tar.bz2 https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--glibc--bleeding-edge-2023.11-1.tar.bz2
      - uses: actions/upload-artifact@v4
        with:
          name: gnu-toolchains
          path: artifacts/*

  download-musl:
    runs-on: ubuntu-latest
    steps:
      - name: Download Musl
        run: |
          mkdir -p artifacts
          cd artifacts
          curl -SL -o amd64-musl-12.3.tar.bz2 https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--musl--stable-2023.08-1.tar.bz2
          curl -SL -o arm64-musl-12.3.tar.bz2 https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--musl--stable-2023.08-1.tar.bz2
          curl -SL -o arm-musl-12.3.tar.bz2 https://toolchains.bootlin.com/downloads/releases/toolchains/armv7/tarballs/armv7--musl--stable-2023.08-1.tar.bz2
          curl -SL -o amd64-musl-13.2.tar.bz2 https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--musl--bleeding-edge-2023.11-1.tar.bz2
          curl -SL -o arm64-musl-13.2.tar.bz2 https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--musl--bleeding-edge-2023.11-1.tar.bz2
          curl -SL -o arm-musl-13.2.tar.bz2 https://toolchains.bootlin.com/downloads/releases/toolchains/armv7/tarballs/armv7--musl--bleeding-edge-2023.11-1.tar.bz2
      - uses: actions/upload-artifact@v4
        with:
          name: musl-toolchains
          path: artifacts/*

  download-extra:
    runs-on: ubuntu-latest
    steps:
      - name: Download Extra
        run: |
          mkdir -p artifacts
          cd artifacts
          # Synology
          curl -SLO https://global.synologydownload.com/download/ToolChain/toolchain/7.1-42661/Realtek%20RTD129x%20Linux%204.4.180/rtd1296-gcc850_glibc226_armv8-GPL.txz 
          curl -SLO https://global.synologydownload.com/download/ToolChain/toolchain/7.1-42661/Intel%20x86%20Linux%204.4.180%20%28GeminiLake%29/geminilake-gcc850_glibc226_x86_64-GPL.txz
          # Docker Tools
          LATEST_ZIP=$(curl -sS https://download.docker.com/win/static/stable/x86_64/ | grep -oE 'docker-[0-9.]+\.zip' | tail -n 1)
          curl -sSLO "https://download.docker.com/win/static/stable/x86_64/$LATEST_ZIP"
          unzip -q $LATEST_ZIP && cp docker/docker.exe docker-windows-x86_64.exe
          URL=$(curl -sS https://api.github.com/repos/docker/compose/releases/latest | jq -r '.assets[] | select(.name == "docker-compose-windows-x86_64.exe") | .browser_download_url')
          curl -sSL -o "docker-compose-windows-x86_64.exe" "$URL"
          # fnpack
          curl -sSL -o fnpack https://static2.fnnas.com/fnpack/fnpack-1.2.0-linux-amd64
          chmod +x fnpack
      - uses: actions/upload-artifact@v4
        with:
          name: extra-resources
          path: |
            artifacts/*.txz
            artifacts/*.exe
            artifacts/fnpack

  create-release:
    needs: [download-gnu, download-musl, download-extra]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: resources
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dpanel-build-resources
          name: "DPanel Build Resources Collection (Parallel)"
          body: "All-in-one build resources for DPanel."
          files: resources/*